#!/usr/bin/bash

SH=$(basename $SHELL)

if [[ $1 == "install" ]]
then
  if [[ $SH == "zsh" ]]
  then
    grep -q "dotfiles prompt=0" ~/.zshrc
    if [[ $? -gt "0" ]]
    then
      printf "\ndotfiles prompt=0" >> ~/.zshrc
    else
      printf "\e[92mtermux-dotfiles\e[0m already installed.\n"
      exit 1
    fi
  elif [[ $SH == "bash" ]]
  then
    grep -q "dotfiles prompt=0" ~/.bashrc
    if [[ $? -gt "0" ]]
    then
      printf "\ndotfiles prompt=0" >> ~/.bashrc
    else
      printf "\e[92mtermux-dotfiles\e[0m already installed.\n"
      exit 1
    fi
  fi
  cp src/program/dotfiles $PREFIX/bin
  cp src/color/onedark.colors ~/.termux/colors.properties
  printf "\e[92mtermux-dotfiles\e[0m successful installed.\nNow you have to restart termux.\n"

elif [[ $1 == "remove" ]]
then
  if [[ $SH == "zsh" ]]
  then
  sed -i '/dotfiles prompt=0/d' ~/.zshrc

elif [[ $SH == "bash" ]]
then
  sed -i '/dotfiles prompt=0/d' ~/.bashrc
fi
  printf "\e[92mtermux-dotfiles\e[0m removed successfully.\n"

else
  printf "install command]─────────────┐\n"
  printf "run \e[92m./$(basename $0) \e[7;92minstall\e[0m ◂────────┘\e[0m\n"
  exit 1
fi
